[features]
seeds = false
skip-lint = false
[programs.devnet]
bookchain_contracts = "Dad4s5C2MTErQtFCwai2DgmskftMPM8iLxrJ3MRXrz62"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/elon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
